config/routes.rb
Rails.application.routes.draw do
  get 'meetup/index'
  #homepage path
  root 'welcome#index'

  #users paths
  get '/signup' => 'users#new', as: "sign_up"
  post '/users' => 'users#create'
  get "/users/:id" => "users#show", as: "user"

  #sessions paths
  get '/login' => 'sessions#new', as: "sign_in"
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: "sign_out"

  #fabrics paths
  get "/fabrics/collection" => "fabrics#index", as: "index_fabrics"
  post "/fabrics/filter" => "fabrics#filter", as: "filter_fabrics"
  get "/fabrics/:id" => "fabrics#show", as: "show_fabrics"

  get "/fabrics/new" => "fabrics#new", as: "new_fabrics" #This serves the form for a new listing
  post "/fabrics/new" => "fabrics#create"#This creates the listing upon submit of form
  delete "/fabrics/:id" => "fabrics#destroy", as: 'delete_fabric' 

  #AUTH ROUTES // DONT TOUCH
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  #meetup routes
  get "/meetup" => "meetup#index", as: "index_events"
end

app/models/fabric.rb
class Fabric < ApplicationRecord
    validates :fabric_name, presence: true
    belongs_to :user
    mount_uploader :image, ImageUploader

    scope :print_scope, -> (print) { where("printed = ? ", true) } #NOT IN USE
    scope :plain_scope, -> (print) { where("printed = ? ", false) } #NOT IN USE
    scope :with_colour, -> (colour) { where(":colour = ANY(colour)", colour: colour ) }
    scope :suitable_for_scope, -> (suitable_for) { where(":suitable_for = ANY(suitable_for)", suitable_for: suitable_for ) }
    scope :with_fibre, -> (fibre) { where(":fibre = ANY(fibre)", fibre: fibre ) }
end

app/controllers/fabrics_controller.rb
class FabricsController < ApplicationController

  def new
    @user = current_user
    #note, because we are using a modal, the info for the new fabric form is passed via the user#show method! 
  end

  def index
    @fabrics = Fabric.where(["user_id = ?", current_user.id]).order(:created_at).reverse
    #arrays for add fabric modal
    @fibres = ["Silk", "Cotton", "Linen", "Wool", "Merino", "Modal", "Bamboo", "Cashmere", "Polyester", "Acetate", "Nylon", "Lurex"]
    @suitable_for = ["Pants", "Skirt", "Shirt", "Dress", "T-Shirt", "Shorts", "Activewear", "Sweater", "Jacket", "Coat", "Swimwear"]
    @colours = ["Red", "Blue", "Orange", "Yellow", "Green", "Purple", "Black", "Grey", "Brown", "Pink", "Metallic"]
  end


  def filter
    #This puts all fabrics through through various filters, if filter submitted.
    @filtered = true
    @fabrics = Fabric.where(["user_id = ?", current_user.id])
    @fabrics = @fabrics.with_colour(params[:filter][:colour]) if params[:filter][:colour].present?
    @fabrics = @fabrics.with_fibre(params[:filter][:fibre]) if params[:filter][:fibre].present?
    @fabrics = @fabrics.suitable_for_scope(params[:filter][:suitable_for]) if params[:filter][:suitable_for].present?
 
    #for pre-selection based on prior search. For pre-selects we need to if/else for the defauls. Although there must be a tidier way to do this!!!
    #DEFINES FILTER BAR PRE-SETS
   if (params[:filter][:fibre]) == ""
      @selected_fibre = "Fibre Type"
    else
      @selected_fibre = (params[:filter][:fibre])
   end

   if (params[:filter][:suitable_for]) == ""
      @selected_suitable_for = "Suitable For"
    else
      @selected_suitable_for = (params[:filter][:suitable_for])
   end

   if (params[:filter][:colour]) == ""
    @selected_colour = "Select Colour"
    else
    @selected_colour = (params[:filter][:colour])
   end
    
    #for add fabric modal
    @fibres = ["Silk", "Cotton", "Linen", "Wool", "Merino", "Modal", "Bamboo", "Cashmere", "Polyester", "Acetate", "Nylon", "Lurex"]
    @suitable_for = ["Pants", "Skirt", "Shirt", "Dress", "T-Shirt", "Shorts", "Activewear", "Sweater", "Jacket", "Coat", "Swimwear"]
    @colours = ["Red", "Blue", "Orange", "Yellow", "Green", "Purple", "Black", "Grey", "Brown", "Pink", "Metallic"]
    render 'index'
  end

  def create 
      @fabric = Fabric.new(fabric_params)
      @fabric.user_id = current_user.id
      
       if @fabric.save
      redirect_to root_path
     else
      render 'new'
    end
  end

  def show
    @fabric = Fabric.find(params[:id])
  end

def destroy
  @fabric = Fabric.find(params[:id])
  if @fabric.destroy
    flash[:success] = "Fabric deleted successfully!"

  end
  respond_to do |format|
    format.html { redirect_to index_fabrics_path }
    format.json { head :no_content }
    format.js { render layout: false }
  end
end

#PRIVATE METHOD TO VALIDATE THE NEW FABRIC FORM
  private
  def fabric_params
    params.require(:fabrics).permit(:fabric_name, :fabric_description, :purchased_from, :meterage, :printed, :image, {suitable_for: []}, {colour: []}, {fibre: []}) 
  end
end

app/views/fabrics/destroy.js.erb
// console.log('Binding event');
// $('.delete_fabric').bind('ajax:success', function() {
//   console.log('fading the element: ', $(this).closest('tr')); 
//   $(this).closest('tr').fadeOut();
// });

// $('.delete_fabric').bind('ajax:success', function() {
//    $(this).closest('tr').fadeOut();
// });


// $('.delete_fabric').bind('ajax:success', function() {
// 	console.log("#fabric_<%=params[:id]%>")
//    $("#fabric_<%=params[:id]%>").fadeOut();
// });


<%if flash[:success].present?%>
  $("#fabric_<%=params[:id]%>").fadeOut();
  //$("#fabric_<%=params[:id]%>").remove();
<%end%>

app/views/fabrics/index.html.erb
<!-- MODEL FOR UPLOAD FABRIC -->

<div id="addfabricbutton">
<!-- Button trigger modal -->
</br><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Add Fabric to collection
</button>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Fabric</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
     


<!-- Form to add fabric -->
<%= form_with scope: :fabrics, url: new_fabrics_path, local: true do |form| %>
    <p>
      <%= form.label :fabric_name %>
  	  <%= form.text_field :fabric_name %></br>

      <%= form.label :fabric_description %>
  	  <%= form.text_field :fabric_description %></br>

      <%= form.label :purchased_from %>
  	  <%= form.text_field :purchased_from %></br>

      <%= form.label :meterage %>
  	  <%= form.select :meterage, (0..500) %></br></br>

    	<%= form.label "SELECT FIBRES" %></br>
		<%@fibres.each do |fibre|%>
		    <%= form.label fibre %>
			<%= form.check_box :fibre, {multiple: true}, fibre.to_s, nil %>
		<% end %></br></br>

    	<%= form.label "SELECT MAIN FABRIC COLOUR" %><br>
		<%@colours.each do |colour|%>
		    <%= form.label colour %>
			<%= form.check_box :colour, {multiple: true}, colour.to_s, nil %>		
		<% end %></br></br>

    	<%= form.label "SUITABLE FOR" %><br>
		<%@suitable_for.each do |item|%>
		    <%= form.label item %>
			<%= form.check_box :suitable_for, {multiple: true}, item.to_s, nil %>		
		<% end %></br></br>

      <%= form.label "PRINTED?" %>
      <%= form.check_box :printed %><br>


<!-- IMAGE UPLOADER -->
      <%= form.label "Upload an Image:"%></br>
    <%= form.file_field :image %></br>
<!-- IMAGE UPLOADER -->
	</p>
<!-- Form to add fabric -->
  </div>

      <div class="modal-footer">
      <!--   BUTTONS -->
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= form.submit "Add Fabric", class: "btn btn-primary" %>
        <!--   BUTTONS -->
        <% end %>  
      </div>
    </div>
  </div>
</div></br></br>


<!-- MODEL FOR UPLOAD FABRIC -->

<div id="filter-section">
  <!-- FILTER HEADER -->
      <h5> Filter your Collection</h5>
  <!-- FILTER HEADER -->


  <!-- FILTER BAR -->

  <% if @filtered == true %>

      <%= form_with scope: :filter, url: filter_fabrics_path, local: true do |form| %>
          <p>
          <%= form.select(:fibre, ['Silk', 'Linen', 'Cotton', 'Bamboo'], {:prompt => "Fibre Type"}) %>
          <%= form.select(:colour, ['Blue', 'Yellow', 'Purple', 'Green'], {:prompt => "Select Colour"}) %>
          <%= form.select(:suitable_for, ['Pants', 'Skit', 'Shirt', 'Skirt'], {:prompt => "Suitable For"}) %>
          <%= form.submit "Filter Results" %> 
          </p>
      <% end %> 

  <% else %> 

      <%= form_with scope: :filter, url: filter_fabrics_path, local: true do |form| %>
          <p>
          <%= form.select(:fibre, ['Silk', 'Linen', 'Cotton', 'Bamboo'], {:prompt => "Fibre Type"})%>
          <%= form.select(:colour, ['Blue', 'Yellow', 'Purple', 'Green'], {:prompt => "Select Colour"})%>
          <%= form.select(:suitable_for, ['Pants', 'Skirt', 'Shirt', 'Activewear'], {:prompt => "Suitable For"})%>
          <%= form.submit "Filter Results" %> 
          </p>
      <% end %>   

  <% end %> 

  <!-- FILTER BAR -->

  <!-- DISPLAYS CURRENTLY SELECTED FIELDS IF @FILTERED VIEW -->
  <div>
  <p><% if @filtered == true %>

      <% if @selected_fibre != "Fibre Type" %>
         <%= "Filtering by Fibre: #{@selected_fibre} "%>
      <% end %></br>  

      <% if @selected_colour != "Select Colour" %>
         <%= "Filtering by Colour: #{@selected_colour} "%>
      <% end %></br>  

      <% if @selected_suitable_for != "Suitable For" %>
         <%= "Filtering by Project: #{@selected_suitable_for} "%></p>
      <% end %></p>
       

   <%= link_to "Clear Filters", index_fabrics_path, class: "btn btn-primary btn-sm" %><br><br>
  <% end %></br>


  <!-- SWITCHES STATEMENT BASED ON FILTERED YES/NO-->
  <% if @fabrics.length == 0 && @filtered == true%>
  	<h4> NO SEARCH RESULTS (PROMOTE FABRICS THAT MATCH SEARCH FROM RETAILER) </h4></br>
    <% else %>

  	<% if @filtered == true %>
  		<h4> OPTIONS FOR YOUR SEWING PROJECT</h4></br>
  	  <% else %>
  		<h4> YOUR FABRIC COLLECTION</h4></br>
  	<% end %>

  <% end %>
<div>


<!-- SHOW FABRIC COLLECTION / FABRIC OPTIONS-->
<div class="card-deck">

    <% @fabrics.each do |fabric| %>
        <div class="col-sm-6 col-md-4 col-lg-3 cardmaster", id="fabric_<%=fabric.id%>">
		    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="<%= fabric.image%>">

        </small></p>

		    <div class="card-body">
		      <h5 class="card-title"><%= fabric.fabric_name%></h5>
		      <p class="card-text"><%= fabric.fabric_description%></p>


<!--               Listing fibre types -->
		      <p class="card-text"><small class="text-muted">Composition: 
				      	
				      	<% fabric.fibre.each do |fibre| %>
				      		<%=fibre %>
				      	<%end%>

<!--               Listing colours -->
		      <p class="card-text"><small class="text-muted">Colours: 
				      	
				      	<% fabric.colour.each do |colour| %>
				      		<%=colour %>
				      	<%end%>
			  </small></p>


<!--               Listing suitable for -->
		      <p class="card-text"><small class="text-muted">Suitable For: 
				      	
				      	<% fabric.suitable_for.each do |item| %>
				      		<%=item %>
				      	<%end%>
			  </small></p>

<!--               Show page button -->
      <%= link_to "Full Details", show_fabrics_path(fabric), class: "btn btn-primary btn-sm" %>

<!--              AJAX DELETE BUTTON // WORKING FUCKNG FINAALLY-->

       <%= link_to "Delete Fabric", delete_fabric_path(fabric), method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'delete_fabric'%>

<!--              AJAX DELETE BUTTON -->

		    </div>
		   </div>
      </div>
    <% end %>



<!-- FLASH MESSAGE GENERATOR - IF FABRIC DELETED -->
  <% if flash[:success] %>
    <div class="success"><%= flash[:success] %></div>
  <% end %>

</div>

app/views/fabrics/show.html.erb
<h1>FABRIC#SHOW PAGE</h1>

<%="Fabric: #{@fabric.fabric_name}" %>


<p> TBC // List fabric details in full here // TBC</p>