config/routes.rb
Rails.application.routes.draw do
  get 'meetup/index'
  #homepage path
  root 'welcome#index'

  #users paths
  get '/signup' => 'users#new', as: "sign_up"
  post '/users' => 'users#create'
  get "/users/:id" => "users#show", as: "user"

  #sessions paths
  get '/login' => 'sessions#new', as: "sign_in"
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: "sign_out"

  #fabrics paths
  get "/fabrics/collection" => "fabrics#index", as: "index_fabrics"
  post "/fabrics/filter" => "fabrics#filter", as: "filter_fabrics"
  get "/fabrics/:id" => "fabrics#show", as: "show_fabrics"

  get "/fabrics/new" => "fabrics#new", as: "new_fabrics" #This serves the form for a new listing
  post "/fabrics/new" => "fabrics#create"#This creates the listing upon submit of form
  delete "/fabrics/:id" => "fabrics#destroy", as: 'delete_fabric' 

  #AUTH ROUTES // DONT TOUCH
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  #meetup routes
  get "/meetup" => "meetup#index", as: "index_events"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myfabricstash</title>

<!--   BOOTSTRAP CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
<!--   BOOTSTRAP CSS -->

<!--   BOOTSTRAP JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
<!--   BOOTSTRAP JS -->  

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



<!--   BOOTSTRAP NAV -->
<div>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">MyFabricStash</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        </li>
        
    <% if @current_user %>

        <li class="nav-item">
            <%= link_to 'Profile', user_path(@current_user), class: 'nav-item nav-link active' %>
        </li>

        <li class="nav-item">
            <%= link_to 'My Collection', index_fabrics_path, class: 'nav-item nav-link active' %>
        </li>

        <li class="nav-item">
            <%= link_to 'Sewing Events', index_events_path, class: 'nav-item nav-link active' %>
        </li>

        <li class="nav-item">
          <%= link_to 'Sign Out', sign_out_path, class: 'nav-item nav-link active', method: :delete %>
        </li>
      </ul>

<!--   SEARCH BAR -->
      <form class="navbar-form navbar-right form-inline ml-auto" role="search">
          <input class="form-control mr-sm-2" type="search" placeholder="Search your Stash" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search
        </form>
<!--   SEARCH BAR -->   

    <% else %>

        <li class="nav-item">
          <%= link_to 'Sign in', sign_in_path, class: 'nav-item nav-link active', method: :get %>
        </li>

        <li class="nav-item">
          <%= link_to 'Sign Up', sign_up_path, class: 'nav-item nav-link active', method: :get %>
        </li>
        </ul>

    <% end %>

    </div>
  </nav>

<!--   BOOTSTRAP NAV -->

    <%= yield %>

  
  </body>
</html>